default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: root
  password: 123456
  # socket: /var/run/mysqld/mysqld.sock
  # socket: /tmp/mysql.sock
development:
  <<: *default
  database: prj2
test:
  <<: *default
  database: prj2_test

staging:
  <<: *default

production:
  <<: *default
  database: prj2_production
