users:
  follow:
    per_page: 20
cities:
  per_page: 15
locations:
  per_page: 20
reviews:
  per_page: 20
comments:
  per_page: 5
images:
  per_page: 50
micro_posts:
  per_page: 20
avatar: "avatar.png"
